import type { Page } from 'playwright';
import { BrowserManager } from '../browser/browserManager.js';
import { env } from '../config/env.js';
import { GenericLMSAdapter } from '../lms/GenericLMSAdapter.js';
import { DeterministicProvider, type AIProvider } from '../ai/AIProvider.js';
import { AutoSubmitPolicy } from '../security/autoSubmitPolicy.js';
import { logger } from '../util/logger.js';
import { RunnerStateMachine, type RunnerState } from './runnerStateMachine.js';
import type { Question, Recommendation } from '../questions/types.js';

export class RunnerOperationError extends Error {
  constructor(public readonly code: 'NO_PENDING_QUESTION' | 'QUESTION_NO_LONGER_PRESENT' | 'BROWSER_SESSION_EXPIRED', public readonly recoverable: boolean) { super(code); }
}
type VideoStatus = { detected: boolean; paused: boolean; currentTime: number; duration: number; ended: boolean };
type Pending = { question: Question; recommendation: Recommendation };

export class Runner {
  private readonly browser = new BrowserManager(); private readonly adapter = new GenericLMSAdapter(); private readonly machine = new RunnerStateMachine();
  private readonly solver: AIProvider; private readonly policy = new AutoSubmitPolicy(env.AUTO_SUBMIT, env.AUTOSUBMIT_ALLOWED_HOSTS.split(','));
  private active = false; private pending?: Pending; private timer?: NodeJS.Timeout; private heartbeatAt?: number; private courseUrl?: string; private lessonUrl?: string; private currentUrl?: string; private video?: VideoStatus;
  constructor(solver: AIProvider = new DeterministicProvider()) { this.solver = solver; }
  status(): { state: RunnerState; active: boolean; browser: boolean; browserStatus: string; browserSessionAgeSeconds: number | undefined; targetMode: string; currentUrl: string | undefined; courseUrl: string | undefined; lessonUrl: string | undefined; questionPending: boolean; pending: Question | undefined; video: VideoStatus | undefined; heartbeatAt: number | undefined } { return { state: this.machine.state, active: this.active, browser: this.browser.connected(), browserStatus: this.browser.connectionStatus(), browserSessionAgeSeconds: this.browser.sessionAgeSeconds(), targetMode: env.TARGET_MODE, currentUrl: this.currentUrl, courseUrl: this.courseUrl, lessonUrl: this.lessonUrl, questionPending: Boolean(this.pending), pending: this.pending?.question, video: this.video, heartbeatAt: this.heartbeatAt }; }
  private move(next: RunnerState, reason: string): void { const event = this.machine.transition(next); logger.info({ module: 'runner', event: 'state_transition', ...event, reason }); }
  async start(): Promise<void> { if (this.active) return; this.pending = undefined; this.active = true; this.heartbeatAt = Date.now(); this.move('RESTORING_SESSION', 'runner started'); this.validateTarget(); const page = await this.browser.page(); await page.goto(env.TARGET_MODE === 'explicit' && env.TARGET_LESSON_URL ? env.TARGET_LESSON_URL : env.LMS_BASE_URL, { waitUntil: 'domcontentloaded' }); this.currentUrl = page.url(); await this.advance(page); this.timer = setInterval(() => void this.tick(), env.QUESTION_POLL_INTERVAL_MS); }
  async pause(): Promise<void> { this.active = false; this.move('PAUSED', 'operator paused runner'); }
  async resume(): Promise<void> { if (!this.active) await this.start(); }
  async stop(): Promise<void> { this.active = false; this.pending = undefined; if (this.timer) clearInterval(this.timer); this.timer = undefined; await this.browser.close(); this.move('COMPLETED', 'operator stopped runner'); }
  private validateTarget(): void { if (env.TARGET_MODE !== 'explicit') return; if (!env.TARGET_LESSON_URL && !env.TARGET_COURSE_URL) throw new Error('EXPLICIT_TARGET_REQUIRED'); for (const candidate of [env.TARGET_LESSON_URL, env.TARGET_COURSE_URL]) if (candidate && new URL(candidate).origin !== new URL(env.LMS_BASE_URL).origin) throw new Error('TARGET_OUTSIDE_LMS_ORIGIN'); }
  private async tick(): Promise<void> { if (!this.active || this.pending) return; this.heartbeatAt = Date.now(); try { if (env.REMOTE_BROWSER_SESSION_MAX_SECONDS && (this.browser.sessionAgeSeconds() ?? 0) >= env.REMOTE_BROWSER_SESSION_MAX_SECONDS) { this.move('RECOVERING', 'remote browser session age limit reached'); await this.browser.close(); return; } const page = await this.browser.page(); this.currentUrl = page.url(); await this.captureVideoState(page); if (this.video?.ended) { this.move('VERIFYING_COMPLETION', 'media ended'); this.move('COMPLETED', 'controlled lesson media completed'); return; } const question = await this.adapter.question(page); if (!question) return; this.move('QUESTION_DETECTED', 'question dialog appeared'); await page.locator('video').evaluate((video: HTMLVideoElement) => video.pause()).catch(() => undefined); await this.captureVideoState(page); this.move('SOLVING_QUESTION', 'extracting recommendation'); const recommendation = await this.solver.solveQuestion(question); this.pending = { question, recommendation }; if (this.policy.permits(question.url)) await this.confirm(recommendation.answerOptionId); else this.move('WAITING_FOR_CONFIRMATION', 'host requires operator confirmation'); } catch (error) { logger.error({ error: error instanceof Error ? error.message : 'unknown' }, 'runner tick failed'); this.pending = undefined; this.move('RECOVERING', 'safe polling recovery'); } }
  private async retryFor(page: Page, selector: string, label: string): Promise<boolean> { for (const delay of [0, 1000, 2000, 4000, 8000]) { if (delay) await new Promise((resolve) => setTimeout(resolve, delay)); if (await page.locator(selector).count()) return true; if (delay) await page.goto(page.url(), { waitUntil: 'domcontentloaded' }).catch(() => undefined); } this.move('RECOVERING', `${label} unavailable after bounded retry`); return false; }
  private async advance(page: Page): Promise<void> { if (page.url().includes('/login')) { this.move('AUTH_REQUIRED', 'login required'); return; } if (env.TARGET_MODE === 'explicit' && env.TARGET_LESSON_URL) { this.lessonUrl = env.TARGET_LESSON_URL; await this.openPlayer(page); return; } if (new URL(page.url()).pathname === '/') { this.move('DASHBOARD', 'dashboard loaded'); this.move('SCANNING_COURSES', 'selecting course'); if (env.TARGET_MODE === 'explicit' && env.TARGET_COURSE_URL) { await page.goto(env.TARGET_COURSE_URL, { waitUntil: 'domcontentloaded' }); this.courseUrl = page.url(); } else { if (!(await this.retryFor(page, '[data-course]', 'course list'))) return; const course = page.locator('[data-course]').first(); await Promise.all([page.waitForURL(/\/course\//), course.click()]); this.courseUrl = page.url(); } } if (page.url().includes('/course/')) { this.move('SCANNING_LESSONS', 'course loaded'); if (!(await this.retryFor(page, '[data-lesson][data-completed="false"]', 'lesson list'))) return; const lesson = page.locator('[data-lesson][data-completed="false"]').first(); this.move('OPENING_LESSON', 'selecting incomplete lesson'); await Promise.all([page.waitForURL(/\/lesson\//), lesson.click()]); this.lessonUrl = page.url(); } if (page.url().includes('/lesson/')) await this.openPlayer(page); }
  private async openPlayer(page: Page): Promise<void> { this.move('DETECTING_PLAYER', 'lesson loaded'); if (!(await this.retryFor(page, 'video', 'player'))) return; await page.locator('video').evaluate((video: HTMLVideoElement, muted: boolean) => { video.muted = muted; void video.play().catch(() => undefined); }, env.MUTE_VIDEO); await this.captureVideoState(page); this.move('PLAYING', 'player started'); }
  private async captureVideoState(page: Page): Promise<void> { this.video = await page.locator('video').evaluate((video: HTMLVideoElement) => ({ detected: true, paused: video.paused, currentTime: video.currentTime, duration: video.duration, ended: video.ended })).catch(() => undefined); }
  async confirm(optionId: string): Promise<void> { const pending = this.pending; if (!pending) throw new RunnerOperationError('NO_PENDING_QUESTION', false); const page = await this.browser.page().catch(() => { throw new RunnerOperationError('BROWSER_SESSION_EXPIRED', true); }); const questionVisible = await page.locator(`[data-question="${pending.question.id}"]`).isVisible().catch(() => false); if (!questionVisible) { this.pending = undefined; throw new RunnerOperationError('QUESTION_NO_LONGER_PRESENT', true); } if (!pending.question.options.some((option) => option.id === optionId)) throw new RunnerOperationError('QUESTION_NO_LONGER_PRESENT', true); this.move('SUBMITTING_ANSWER', 'operator selected answer'); const index = await page.locator('input').evaluateAll((inputs, id) => inputs.findIndex((input) => input instanceof HTMLInputElement && input.value === id), optionId); if (index < 0) throw new RunnerOperationError('QUESTION_NO_LONGER_PRESENT', true); await page.locator('input').nth(index).check(); await page.getByRole('button', { name: /submit/i }).click(); this.move('VERIFYING_ANSWER', 'waiting for acknowledgement'); await page.locator('[data-question]').waitFor({ state: 'hidden', timeout: 5000 }).catch(() => { throw new RunnerOperationError('QUESTION_NO_LONGER_PRESENT', true); }); this.pending = undefined; this.move('RESUMING_VIDEO', 'answer acknowledged'); await page.locator('video').evaluate((video: HTMLVideoElement) => void video.play()).catch(() => undefined); await this.captureVideoState(page); this.move('PLAYING', 'video resumed'); }
}
